spring.application.name=projeta.dev

spring.datasource.url=jdbc:postgresql://localhost:5432/projection_dev
spring.datasource.username=postgres
spring.datasource.password=1131

spring.jpa.hibernate.ddl-auto=create-drop