ALTER TABLE tb_user
ADD COLUMN about TEXT,
ADD COLUMN cover_url TEXT,
ADD COLUMN perfil_url TEXT,
ADD COLUMN link1 TEXT,
ADD COLUMN link2 TEXT,
ADD COLUMN link3 TEXT,
ADD COLUMN link4 TEXT,
ADD COLUMN link5 TEXT;

